apiVersion: serviceaccount.authn.krateo.io/v1alpha1
kind: ServiceAccount
metadata:
  name: {{`{{ .name }}`}}
  namespace: {{`{{ .namespace }}`}}
spec:
  serviceAccountRef:
    namespace: {{`{{ .saNamespace }}`}}
    name: {{`{{ .saName }}`}}
  groups:
    - "{{`{{ .group }}`}}"
  displayName: "{{`{{ .displayName }}`}}"
